#!/usr/bin/env python3
"""
Cache US market holidays from Finnhub into a generated frontend module.

This script is meant to run outside market hours. The app imports the generated
module at build/runtime, so no user request hits Finnhub for calendar data.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import requests

from provider_market_hours import block_finnhub_reserved_window
from sync_finnhub_earnings import load_local_env


REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "apps" / "frontend" / "lib" / "marketHolidays.generated.ts"
BASE_URL = "https://finnhub.io/api/v1/stock/market-holiday"


def fetch_holidays(token: str, exchange: str) -> dict[str, Any]:
    resp = requests.get(
        BASE_URL,
        params={"exchange": exchange, "token": token},
        timeout=30,
    )
    if not resp.ok:
        raise RuntimeError(f"Finnhub market-holiday HTTP {resp.status_code}: {resp.text[:300]}")
    body = resp.json()
    if not isinstance(body, dict) or not isinstance(body.get("data"), list):
        raise RuntimeError(f"Unexpected Finnhub market-holiday response: {str(body)[:300]}")
    return body


def split_holidays(rows: list[dict[str, Any]]) -> tuple[list[str], dict[str, str]]:
    closed: set[str] = set()
    early_closes: dict[str, str] = {}
    for row in rows:
        at_date = str(row.get("atDate") or row.get("date") or "").strip()
        if len(at_date) < 10:
            continue
        iso = at_date[:10]
        trading_hour = str(row.get("tradingHour") or "").strip()
        if trading_hour:
            early_closes[iso] = trading_hour
        else:
            closed.add(iso)
    return sorted(closed), dict(sorted(early_closes.items()))


def read_existing_generated() -> tuple[list[str], dict[str, str]] | None:
    if not OUTPUT_PATH.exists():
        return None
    text = OUTPUT_PATH.read_text()
    holiday_match = re.search(
        r"MARKET_HOLIDAYS_US\s*=\s*\[(.*?)\]\s+as const",
        text,
        re.S,
    )
    early_match = re.search(
        r"MARKET_EARLY_CLOSES_US[^=]*=\s*\{(.*?)\};",
        text,
        re.S,
    )
    if not holiday_match:
        return None
    closed = sorted(
        re.findall(r"""["'](\d{4}-\d{2}-\d{2})["']""", holiday_match.group(1))
    )
    early_closes: dict[str, str] = {}
    if early_match:
        for day, hours in re.findall(
            r"""["'](\d{4}-\d{2}-\d{2})["']\s*:\s*["']([^"']+)["']""",
            early_match.group(1),
        ):
            early_closes[day] = hours
    return closed, dict(sorted(early_closes.items()))


def ts_string(value: str) -> str:
    return json.dumps(value)


def write_generated(
    closed: list[str],
    early_closes: dict[str, str],
    *,
    provider: str,
    exchange: str,
    timezone_name: str,
) -> None:
    lines = [
        "// Generated by scripts/sync_finnhub_market_holidays.py.",
        "// Do not edit by hand; run the script after market hours instead.",
        "",
        "export const MARKET_HOLIDAY_SOURCE = {",
        f"  provider: {ts_string(provider)},",
        f"  exchange: {ts_string(exchange)},",
        f"  generatedAt: {ts_string(datetime.now(timezone.utc).isoformat())},",
        f"  timezone: {ts_string(timezone_name)},",
        "} as const;",
        "",
        "export const MARKET_HOLIDAYS_US = [",
    ]
    lines.extend(f"  {ts_string(day)}," for day in closed)
    lines.extend([
        "] as const;",
        "",
        "export const MARKET_EARLY_CLOSES_US: Record<string, string> = {",
    ])
    lines.extend(
        f"  {ts_string(day)}: {ts_string(hours)},"
        for day, hours in early_closes.items()
    )
    lines.extend(["};", ""])
    OUTPUT_PATH.write_text("\n".join(lines))


def main() -> int:
    load_local_env()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exchange", default="US")
    parser.add_argument(
        "--allow-missing-key",
        action="store_true",
        help="Exit 0 instead of failing when FINNHUB_API_KEY is missing.",
    )
    parser.add_argument(
        "--allow-market-hours",
        action="store_true",
        help="Allow non-price Finnhub calls during the 09:25-16:45 ET quote refresh window.",
    )
    args = parser.parse_args()

    token = os.getenv("FINNHUB_API_KEY")
    if not token:
        msg = "FINNHUB_API_KEY missing"
        if args.allow_missing_key:
            print(f"{msg}; skipping market holiday sync")
            return 0
        print(msg, file=sys.stderr)
        return 1

    block_finnhub_reserved_window(args.allow_market_hours)
    body = fetch_holidays(token, args.exchange)
    closed, early_closes = split_holidays(body.get("data") or [])
    if not closed:
        print("Finnhub returned no full market holidays; refusing to overwrite cache", file=sys.stderr)
        return 1

    existing = read_existing_generated()
    if existing == (closed, early_closes):
        print(
            f"{OUTPUT_PATH.relative_to(REPO_ROOT)} already matches Finnhub "
            f"({len(closed)} full holidays, {len(early_closes)} early closes)"
        )
        return 0

    write_generated(
        closed,
        early_closes,
        provider="finnhub /stock/market-holiday",
        exchange=str(body.get("exchange") or args.exchange),
        timezone_name=str(body.get("timezone") or "America/New_York"),
    )
    print(
        f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} "
        f"({len(closed)} full holidays, {len(early_closes)} early closes)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
