export const COMPANY_NAMES: Record<string, string> = {
  AAPL: 'Apple Inc.',
  MSFT: 'Microsoft',
  AMZN: 'Amazon',
  NVDA: 'NVIDIA',
  GOOGL: 'Alphabet',
  META: 'Meta Platforms',
  TSLA: 'Tesla',
  NFLX: 'Netflix',
  JPM: 'JPMorgan Chase',
  V: 'Visa',
  MA: 'Mastercard',
  WFC: 'Wells Fargo',
  GS: 'Goldman Sachs',
  BAC: 'Bank of America',
  UNH: 'UnitedHealth',
  LLY: 'Eli Lilly',
  PFE: 'Pfizer',
  ABBV: 'AbbVie',
  BMY: 'Bristol-Myers',
  GILD: 'Gilead',
  HUM: 'Humana',
  XOM: 'Exxon Mobil',
  CVX: 'Chevron',
  COP: 'ConocoPhillips',
  AMD: 'AMD',
  AVGO: 'Broadcom',
  CRM: 'Salesforce',
  ADBE: 'Adobe',
  INTC: 'Intel',
  QCOM: 'Qualcomm',
  CSCO: 'Cisco',
  COIN: 'Coinbase',
  SNOW: 'Snowflake',
  PLTR: 'Palantir',
  HD: 'Home Depot',
  MCD: "McDonald's",
  SBUX: 'Starbucks',
  NKE: 'Nike',
  KO: 'Coca-Cola',
  PEP: 'PepsiCo',
  DIS: 'Disney',
  BA: 'Boeing',
  CAT: 'Caterpillar',
  LIN: 'Linde',
  T: 'AT&T',
  VZ: 'Verizon',
};
