"""
Generate apps/frontend/lib/popular.ts from 90-day dollar volume.

The "Popular" filter on the earnings calendar reflects what real
people are actually trading. After empirically testing a composite
(dollar volume × S&P 500 membership × options chain breadth), pure
dollar volume rank scored highest on coverage of retail favorites
(MSTR/HOOD/PLTR/COIN/CRWV/RKLB/NBIS/IREN/ASTS/CVNA/SHOP/BABA/TSM/UBER)
without sacrificing the mega-cap names everyone expects to see
(NVDA/TSLA/AAPL/MSFT/AMZN/META/GOOGL/BRK.B/LLY).

Adding S&P 500 or chain-breadth weight to a composite trades retail
coverage for sleepy-large-cap coverage (MMM, BLK), which is the wrong
trade for an earnings calendar where the popular set should highlight
movers.

Why dollar volume — not just share volume — is the right metric:
- It's split-invariant. NVDA pre-split (10M shares × $2000) = post-split
  (100M shares × $200) = same dollar volume.
- Penny stocks self-filter out: 1B shares × $0.20 = $200M, while
  100M shares × $200 = $20B. Capital flow matters, share count alone
  doesn't.
- Captures retail favorites: high-flow names like MSTR/PLTR/HOOD all
  rank in the top 50 because real money is moving in/out daily.

Filtered to symbols in v_earnings so ETFs (SPY/QQQ/etc.) don't crowd
out actual reporting companies.

Output: top 100 → apps/frontend/lib/popular.ts, weights 76..100 linear
by rank. The frontend filter is `POPULAR_WEIGHT[ticker] >= 76`, so all
100 stay above the cutoff and sort order respects rank.

Regenerated nightly in CI alongside the daily JSONs.
"""
from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

import duckdb

REPO_ROOT = Path(__file__).resolve().parent.parent
DB_PATH = REPO_ROOT / "data" / "quantiv.duckdb"
OUT_PATH = REPO_ROOT / "apps" / "frontend" / "lib" / "popular.ts"
TOP_N = 200
WINDOW_DAYS = 90
MIN_WEIGHT = 76  # must match the >=76 filter in EarningsGrid.tsx
MAX_WEIGHT = 100


def weight_for_rank(rank: int, total: int) -> int:
    """Linear: rank 1 → MAX_WEIGHT, rank total → MIN_WEIGHT."""
    if total <= 1:
        return MAX_WEIGHT
    span = MAX_WEIGHT - MIN_WEIGHT
    return round(MAX_WEIGHT - (rank - 1) * span / (total - 1))


def main() -> int:
    if not DB_PATH.exists():
        print(f"❌ DuckDB not found at {DB_PATH}", file=sys.stderr)
        return 1

    conn = duckdb.connect(str(DB_PATH), read_only=True)
    rows = conn.execute(
        f"""
        WITH dollar_vol AS (
            SELECT act_symbol, SUM(volume * close) AS dv
            FROM v_ohlcv
            WHERE date >= CURRENT_DATE - INTERVAL '{WINDOW_DAYS}' DAY
              AND volume IS NOT NULL
              AND close IS NOT NULL
            GROUP BY act_symbol
        ),
        earners AS (SELECT DISTINCT act_symbol FROM v_earnings)
        SELECT d.act_symbol, d.dv,
               ROW_NUMBER() OVER (ORDER BY d.dv DESC) AS rank
        FROM dollar_vol d
        JOIN earners e USING (act_symbol)
        QUALIFY rank <= {TOP_N}
        ORDER BY rank
        """
    ).fetchall()

    if not rows:
        print("❌ No rows returned from v_ohlcv × v_earnings query", file=sys.stderr)
        return 1

    total = len(rows)
    entries: list[str] = []
    for ticker, _dv, rank in rows:
        w = weight_for_rank(rank, total)
        # Quote keys so dotted tickers (BRK.B, BF.B, GRP.U) stay
        # valid TypeScript object literals.
        entries.append(f'  "{ticker}": {w},')

    now_iso = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    content = (
        "// AUTO-GENERATED by tools/build_popular_weights.py — DO NOT EDIT BY HAND.\n"
        "// Top tickers by 90-day dollar volume (volume × close) from v_ohlcv,\n"
        "// filtered to symbols with earnings (v_earnings). Split-invariant by\n"
        "// construction; captures both mega-cap and retail-favorite names.\n"
        "// Regenerated nightly; rank 1 → weight 100, rank 100 → weight 76.\n"
        f"// Last generated: {now_iso}.\n"
        "\n"
        "export const POPULAR_WEIGHT: Record<string, number> = {\n"
        + "\n".join(entries)
        + "\n};\n"
    )
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(content)
    print(f"✅ Wrote {total} popular tickers → {OUT_PATH.relative_to(REPO_ROOT)}")
    print(f"   Top 5:    {', '.join(t for t, _, _ in rows[:5])}")
    print(f"   Bottom 5: {', '.join(t for t, _, _ in rows[-5:])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
