"""
Generate apps/frontend/lib/popular.ts from actual dollar volume.

The "Popular" filter on the earnings calendar reflects what's being
traded, not a static hand-curated list. Each nightly CI run rebuilds
this file so retail favorites (HOOD, MSTR, PLTR, COIN), recent IPOs
(CRWV, RKLB, NBIS, IREN), and non-S&P liquid names (TSM, ASML, BABA,
SHOP) get included automatically as their flow shifts.

Methodology:
  rank tickers by SUM(volume × close) over the last 90 days
  filter to tickers that appear in v_earnings (drops ETFs)
  take top 100
  map rank 1..100 → weight 100..76 (linear)

The frontend filter is `POPULAR_WEIGHT[ticker] >= 76` (apps/frontend/
components/EarningsGrid.tsx), so all 100 stay above the cutoff and the
sort order respects rank.

Generated file is committed alongside the daily refresh JSONs.
"""
from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

import duckdb

REPO_ROOT = Path(__file__).resolve().parent.parent
DB_PATH = REPO_ROOT / "data" / "quantiv.duckdb"
OUT_PATH = REPO_ROOT / "apps" / "frontend" / "lib" / "popular.ts"
TOP_N = 100
WINDOW_DAYS = 90
MIN_WEIGHT = 76  # must match the >=76 filter in EarningsGrid.tsx
MAX_WEIGHT = 100


def weight_for_rank(rank: int, total: int) -> int:
    """Linear interpolation: rank 1 → MAX_WEIGHT, rank total → MIN_WEIGHT."""
    if total <= 1:
        return MAX_WEIGHT
    span = MAX_WEIGHT - MIN_WEIGHT
    return round(MAX_WEIGHT - (rank - 1) * span / (total - 1))


def main() -> int:
    if not DB_PATH.exists():
        print(f"❌ DuckDB not found at {DB_PATH}", file=sys.stderr)
        return 1

    conn = duckdb.connect(str(DB_PATH), read_only=True)
    rows = conn.execute(
        f"""
        WITH dollar_vol AS (
            SELECT act_symbol, SUM(volume * close) AS dv
            FROM v_ohlcv
            WHERE date >= CURRENT_DATE - INTERVAL '{WINDOW_DAYS}' DAY
              AND volume IS NOT NULL
              AND close IS NOT NULL
            GROUP BY act_symbol
        ),
        earners AS (SELECT DISTINCT act_symbol FROM v_earnings)
        SELECT d.act_symbol, d.dv,
               ROW_NUMBER() OVER (ORDER BY d.dv DESC) AS rank
        FROM dollar_vol d
        JOIN earners e USING (act_symbol)
        QUALIFY rank <= {TOP_N}
        ORDER BY rank
        """
    ).fetchall()

    if not rows:
        print("❌ No rows returned from v_ohlcv × v_earnings query", file=sys.stderr)
        return 1

    total = len(rows)
    entries: list[str] = []
    for ticker, _dv, rank in rows:
        w = weight_for_rank(rank, total)
        # Quote the key so dotted tickers (BRK.B, BF.B, GRP.U) stay
        # valid TypeScript object literals.
        entries.append(f'  "{ticker}": {w},')

    now_iso = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    content = (
        "// AUTO-GENERATED by tools/build_popular_weights.py — DO NOT EDIT BY HAND.\n"
        "// Ranks the top tickers by 90-day dollar volume (volume × close)\n"
        "// from v_ohlcv, filtered to symbols that have earnings (v_earnings).\n"
        "// Regenerated nightly; rank 1 → weight 100, rank 100 → weight 76.\n"
        f"// Last generated: {now_iso}.\n"
        "\n"
        "export const POPULAR_WEIGHT: Record<string, number> = {\n"
        + "\n".join(entries)
        + "\n};\n"
    )
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(content)
    print(f"✅ Wrote {total} popular tickers → {OUT_PATH.relative_to(REPO_ROOT)}")
    print(f"   Top 5: {', '.join(t for t, _, _ in rows[:5])}")
    print(f"   Bottom 5: {', '.join(t for t, _, _ in rows[-5:])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
